// Auto-generated by rtlgen.py -- DO NOT EDIT BY HAND
//
// Config: baseline_conservative
//
// Architecture (held IDENTICAL across every candidate design, see guide 3.1):
//   direct-form, symmetric-folded, fully-parallel FIR
//     y = C_center * sr[center] + sum_{i< n_pairs} C_i * (sr[i] + sr[N-1-i])
//   * symmetric folding halves the multiplier count (8 folded + 1 center)
//   * fully parallel: 1 sample in / 1 sample out per clock, throughput identical
//     across candidates
//   * fixed pipeline depth: input register -> accumulator register -> output
//     register (the testbench aligns on this; do not change one template only)
//
// This module is generated for ONE fixed-point configuration. The parameters
// below document that configuration and are used for the port widths; the
// internal wire widths are emitted as literal constants for each config, so
// the parameters must NOT be overridden at instantiation time.
//
// Coefficient widths (bits, per unique tap, folded pairs then center):
//   [12, 12, 12, 12, 12, 12, 12, 12, 12]
// Per-tap binary-point alignment shift (bits appended at the LSB of each
// product so all terms share one binary point):
//   [0, 0, 0, 0, 0, 0, 0, 0, 0]
//
// coeff: Q2.10 (max frac width used)
// input: Q2.14
// acc:   signed 37 bits, fraction at bit 24
// out:   Q2.14
// requantize: >>> 10, rounding=round, saturate=True
//
// Licensed under the Apache License, Version 2.0. See the repo LICENSE file.

module fir_baseline_conservative #(
    parameter N_TAPS      = 17,
    parameter IN_WIDTH    = 16,
    parameter OUT_WIDTH   = 16,
    parameter COEFF_WIDTH = 12,
    parameter ACC_WIDTH   = 37
) (
    input  wire                        clk,
    input  wire                        rst_n,
    input  wire                        in_valid,
    input  wire signed [IN_WIDTH-1:0]  in_data,
    output reg                         out_valid,
    output reg  signed [OUT_WIDTH-1:0] out_data
);

    // ---- symmetric-folded coefficient constants (hardwired, signed) -------------
    // Emitted as sized two's-complement hex patterns so negative constants are
    // unambiguous and exactly the allocated width.
    localparam signed [11:0] C0 = 12'sh005;
    localparam signed [11:0] C1 = 12'shffc;
    localparam signed [11:0] C2 = 12'shfea;
    localparam signed [11:0] C3 = 12'shfda;
    localparam signed [11:0] C4 = 12'shfe8;
    localparam signed [11:0] C5 = 12'sh02a;
    localparam signed [11:0] C6 = 12'sh094;
    localparam signed [11:0] C7 = 12'sh0f8;
    localparam signed [11:0] C8 = 12'sh122;

    // ---- input delay line (N_TAPS deep shift register) --------------------------
    reg signed [IN_WIDTH-1:0] sr [0:N_TAPS-1];
    integer i;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            for (i = 0; i < N_TAPS; i = i + 1) sr[i] <= {IN_WIDTH{1'b0}};
        end else if (in_valid) begin
            sr[0] <= in_data;
            for (i = 1; i < N_TAPS; i = i + 1) sr[i] <= sr[i-1];
        end
    end

    // ---- symmetric pre-adders: explicit sign extension, no implicit width promotion
    wire signed [16:0] fold0 =
        {sr[0][IN_WIDTH-1], sr[0]} + {sr[16][IN_WIDTH-1], sr[16]};
    wire signed [16:0] fold1 =
        {sr[1][IN_WIDTH-1], sr[1]} + {sr[15][IN_WIDTH-1], sr[15]};
    wire signed [16:0] fold2 =
        {sr[2][IN_WIDTH-1], sr[2]} + {sr[14][IN_WIDTH-1], sr[14]};
    wire signed [16:0] fold3 =
        {sr[3][IN_WIDTH-1], sr[3]} + {sr[13][IN_WIDTH-1], sr[13]};
    wire signed [16:0] fold4 =
        {sr[4][IN_WIDTH-1], sr[4]} + {sr[12][IN_WIDTH-1], sr[12]};
    wire signed [16:0] fold5 =
        {sr[5][IN_WIDTH-1], sr[5]} + {sr[11][IN_WIDTH-1], sr[11]};
    wire signed [16:0] fold6 =
        {sr[6][IN_WIDTH-1], sr[6]} + {sr[10][IN_WIDTH-1], sr[10]};
    wire signed [16:0] fold7 =
        {sr[7][IN_WIDTH-1], sr[7]} + {sr[9][IN_WIDTH-1], sr[9]};

    // ---- constant multipliers (one per unique coefficient) ----------------------
    wire signed [28:0] prod0 = fold0 * C0;
    wire signed [28:0] prod1 = fold1 * C1;
    wire signed [28:0] prod2 = fold2 * C2;
    wire signed [28:0] prod3 = fold3 * C3;
    wire signed [28:0] prod4 = fold4 * C4;
    wire signed [28:0] prod5 = fold5 * C5;
    wire signed [28:0] prod6 = fold6 * C6;
    wire signed [28:0] prod7 = fold7 * C7;
    wire signed [27:0] prod_center = sr[8] * C8;

    // ---- binary-point alignment + sign extension to the accumulator width --------
    // Each term is padded at the LSB by its alignment shift and sign-extended to
    // ACC_WIDTH. Doing this explicitly (instead of relying on Verilog's implicit
    // context-width promotion) is what makes this template bit-exact against the
    // Python golden model.
    wire signed [28:0] term0 = prod0;
    wire signed [28:0] term1 = prod1;
    wire signed [28:0] term2 = prod2;
    wire signed [28:0] term3 = prod3;
    wire signed [28:0] term4 = prod4;
    wire signed [28:0] term5 = prod5;
    wire signed [28:0] term6 = prod6;
    wire signed [28:0] term7 = prod7;
    wire signed [28:0] term8 = {prod_center[27], prod_center};

    wire signed [ACC_WIDTH-1:0] acc_sum = {{8{term0[28]}}, term0} + {{8{term1[28]}}, term1} + {{8{term2[28]}}, term2} + {{8{term3[28]}}, term3} + {{8{term4[28]}}, term4} + {{8{term5[28]}}, term5} + {{8{term6[28]}}, term6} + {{8{term7[28]}}, term7} + {{8{term8[28]}}, term8};

    // ---- accumulator pipeline register ------------------------------------------
    reg signed [ACC_WIDTH-1:0] acc_reg;
    reg                        valid_pipe;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            acc_reg    <= {ACC_WIDTH{1'b0}};
            valid_pipe <= 1'b0;
        end else begin
            acc_reg    <= acc_sum;
            valid_pipe <= in_valid;
        end
    end

    // ---- requantize: round, shift down to the output format, saturate/wrap ------
    localparam SHIFT = 10;   // requantization right shift
    localparam signed [ACC_WIDTH:0] ROUND_CONST = 38'sh0000000200;
    // One guard bit above the accumulator holds the rounding constant without
    // wrapping.
    wire signed [ACC_WIDTH:0] rounded = {acc_reg[ACC_WIDTH-1], acc_reg} + ROUND_CONST;
    // Arithmetic shift right by SHIFT, expressed as a bit-select of the upper
    // ACC_WIDTH+1-SHIFT bits. (Do NOT write `shifted = rounded >>> SHIFT` into a
    // narrower wire: the arithmetic shift sign-fills the LOW bits and the
    // assignment then truncates the MSBs, keeping the sign-fill instead of the
    // result -- a classic, silent Verilog bug.)
    wire signed [27:0] shifted = rounded[37:10];

    // output-format limits, already sign-extended to the shifted width
    localparam signed [27:0] OUT_MAX = 28'sh0007fff;
    localparam signed [27:0] OUT_MIN = 28'shfff8000;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            out_data  <= {OUT_WIDTH{1'b0}};
            out_valid <= 1'b0;
        end else begin
            if (shifted > OUT_MAX)
                out_data <= OUT_MAX[OUT_WIDTH-1:0];
            else if (shifted < OUT_MIN)
                out_data <= OUT_MIN[OUT_WIDTH-1:0];
            else
                out_data <= shifted[OUT_WIDTH-1:0];
            out_valid <= valid_pipe;
        end
    end

endmodule
